### PR TITLE
Created basic codable response representation

### PR DESCRIPTION
**Pull request by Davidde94**

### CODE REVIEW

**Comment by Davidde94** [comment]
PayloadType is a generic constraint allowing you to customise the response. E.g. you could set the type to an array of `Int` if you wanted, and what would create a response with `[Int]` as the payload.

**Comment by RyanMKrol** [comment]
Is PayloadType also a swift thing?

**Comment by Davidde94** [comment]
Nope, generic constraint on line 12 (forced to conform to Codable)

**Comment by RyanMKrol** [comment]
You don’t have to define it further than that?

**Comment by Davidde94** [comment]
Nope, just a type alias. I could have used the standard `T` but thought `PayloadType` was more explicit.

**Comment by RyanMKrol** [comment]
Gotcha

**Pull request merged**
